Algoritmo "circulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/07/2020
Var
// Seção de Declarações das variáveis 
   area, r : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Informe o valor do raio.: ")
   leia(r)
   area <- pi * exp(r,2)
   Escreva("A área do círculo.: ", area:4:3, "m²")

Fimalgoritmo