Algoritmo "soma"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/07/2020
Var
// Seção de Declarações das variáveis 
   soma, x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Informe o valor de X: ")
   leia(x)
   Escreva("Informe o valor de y: ")
   leia(y)
   soma <- x + y
   Escreva("A soma de ", x, " e ", y, " = ", soma)
   

Fimalgoritmo